# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #backup - uses: actions/checkout@v3
        steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches
        contents: read

   - name: Run markdown lint
     run: |
       npm install remark-cli remark-preset-lint-consistent
       npx remark . --use remark-preset-lint-consistent --frail
       contents: write
